#ShaderCycler auto-applied shader for dimension
#Sun Sep 20 21:00:45 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=Mellow Shader v3.3.zip
enableShaders=true
